Contributing + Under Development
Allaman/system-design-primer pull request #30
Opened 2021-02-19 19:06 UTC by JacobK233811

Add translations to the README-de.md file to include the Contributing and Under Development sections.

2021-02-21 14:54 UTC, Allaman requested changes

2021-02-21 14:54 UTC, Allaman commented on README-de.md
> +## Beitragungen
Ich würde "Mitwirken" sagen

2021-02-21 14:54 UTC, Allaman commented on README-de.md
> +Fühlen Sie frei zum Pull Requests vorlegen zum helfen:
Zögere nicht durch Pull Requests zu helfen

2021-02-21 14:54 UTC, Allaman commented on README-de.md
> +Inhalte dass etwa aufpolieren braucht finden sich [in Entwicklung](#in-entwicklung).
Inhalte die etwas verbessert werden können finden sich ...

2021-02-21 14:54 UTC, Allaman commented on README-de.md
> +Inspizieren Sie die [Beitragende Richtlinien](CONTRIBUTING.md).
Beachte die [Richtlinien zum Mitwirken]...

2021-02-21 14:54 UTC, Allaman commented on README-de.md
> +Interessiert Sie sich auf ein Abschnitt hinzufügen oder eins dass in Bearbeitung ist ergänzen?  [Beitragen](#beitragungen)!
Interessiert ein Abschnitt Hinzufügen oder einen in Bearbeitung zu ergänzen?  ...

2021-02-21 14:54 UTC, Allaman commented on README-de.md
> +* [Beitragen](#beitragungen)
Unterstützen

2021-02-21 14:54 UTC, Allaman commented on README-de.md
> +* [Beitragen](#beitragungen)
Allgemein würde ich statt dem "Sie" das "Du" bevorzugen. Sie klingt irgenwie so steif und förmlich... Was meinst du dazu?

2021-02-21 15:29 UTC, JacobK233811 commented on README-de.md
> +## Beitragungen
Verstanden.

2021-02-21 15:29 UTC, JacobK233811 commented on README-de.md
> +Fühlen Sie frei zum Pull Requests vorlegen zum helfen:
Ich werde es korrigieren.

2021-02-21 15:40 UTC, JacobK233811 commented on README-de.md
> +* [Beitragen](#beitragungen)
Ich kann das

2021-02-21 15:50 UTC, JacobK233811 commented
Thanks for the pointers. Made the suggested edits and I'll work on using "Du" instead of "Sie" throughout. If you give it a once-over to ensure it looks alright, should be ready to merge and I can jump on another couple of issues.

2021-02-26 03:29 UTC, JacobK233811 commented
Ready to merge and close @Allaman ?

2021-02-27 20:44 UTC, Allaman approved these changes
sry I was busy 
Besides the comment everything looks good

2021-02-27 20:44 UTC, Allaman commented on README-de.md
> +* Konsistentes Streuspeicherverfahren (Consistent hashing)
sry i was busy :/ 

Pls dont translate "hash" with "Streuspeicherverfahren". I dont even know this german word :D

2021-02-27 21:21 UTC, JacobK233811 commented on README-de.md
> +* Konsistentes Streuspeicherverfahren (Consistent hashing)
Such a fun word though :P I changed it back 👍🏼

2021-02-27 21:22 UTC, merged