Add translation for availability vs consistency
Allaman/system-design-primer pull request #32
Opened 2021-03-19 12:47 UTC by dominikbraun

Closes #12.

2021-03-20 21:20 UTC, Allaman requested changes
Bis meine minor Anmerkungen top :)

2021-03-20 21:20 UTC, Allaman commented on README-de.md
> +*Netzwerke sind nie zuverlässig, weshalb du Ausfalltoleranz unterstützen und zwischen Konsisten und Verfügbarkeit abwägen müssen wirst.*
"Konsisten und Verfügbarkeit" meint Konsistenz und Verfügbarkeit?

2021-03-20 21:20 UTC, Allaman commented on README-de.md
> +AP ist eine gute Wahl, wenn die Geschäftsanforderungen [Eventual Consistency](#eventual-consistency) erlauben oder wenn das System auch trotz Fehlern von Außerhalb weiterarbeiten muss.
Im Index habe ich es so übersetzt. Wenn das für dich passt bitte den Link updaten
`[Eventuelle Konsistenz](#eventuelle-konsistenz)`

2021-03-20 21:50 UTC, dominikbraun commented on README-de.md
> +*Netzwerke sind nie zuverlässig, weshalb du Ausfalltoleranz unterstützen und zwischen Konsisten und Verfügbarkeit abwägen müssen wirst.*
Danke!

2021-03-20 21:52 UTC, dominikbraun commented on README-de.md
> +AP ist eine gute Wahl, wenn die Geschäftsanforderungen [Eventual Consistency](#eventual-consistency) erlauben oder wenn das System auch trotz Fehlern von Außerhalb weiterarbeiten muss.
Das ist ein False Friend: "Eventual" bedeutet "schließlich/letztendlich". Einen geläufigen deutschen Begriff für Eventual Consistency scheint es nicht zu geben, auch Wikipedia verwendet "Eventual Consistency" als Eigenbegriff: https://de.wikipedia.org/wiki/Konsistenz_(Datenspeicherung)#Verteilte_Systeme

2021-03-21 22:02 UTC, Allaman commented on README-de.md
> +AP ist eine gute Wahl, wenn die Geschäftsanforderungen [Eventual Consistency](#eventual-consistency) erlauben oder wenn das System auch trotz Fehlern von Außerhalb weiterarbeiten muss.
ich mag false friends nicht :see_no_evil:

2021-03-21 22:02 UTC, merged