Add Section "How to approach a system design interview question"
Allaman/system-design-primer pull request #33
Opened 2021-07-04 15:08 UTC by JacobK233811

Wie ein System-Design Interview Frage zu angehen

2021-07-06 19:25 UTC, Allaman requested changes
Danke dir :)

2021-07-06 19:25 UTC, Allaman commented on README-de.md
> +## Wie ein System-Design Interview Frage zu angehen
Wie man eine System-Design Interview Frage angehen soll

2021-07-06 19:25 UTC, Allaman commented on README-de.md
> +> Wie ein System-Design Interview Frage zu anpacken.
Wie man eine ... Frage anzupacken hat

2021-07-06 19:25 UTC, Allaman commented on README-de.md
> +Das System-Design Interview ist ein **unbegrenzt Gespräch**.  Du solltest es bestimmen.
**offenenes Gespräch**. Die Führung des Gesprächs wird von dir erwartet.

2021-07-06 19:25 UTC, Allaman commented on README-de.md
> +Du kannst die folgende Schritte nutzen um die Diskussion zu leiten.  Um sich diese Vorgang zu festigen, arbeite dich durch [System design interview questions with solutions](#system-design-interview-
Zur Festigung dieses Prozesses, arbeite dich durch den ... Abschnitt mit den folgenden Schritten.

2021-07-06 19:25 UTC, Allaman commented on README-de.md
> +Sammelt Anforderungen und Weit das Problem aus.  Stelle Fragen um Anwendungsfälle und Grenzen zu klarmachen.  Diskutiert die Annahmen.
Sammle Anforderungen und erfasse das Problem. [....] Diskutiere die Annahmen.

2021-07-06 19:25 UTC, Allaman commented on README-de.md
> +* Wie viel Daten erwarten wir zu handeln?
Wie viele Daten, welches das System verarbeitet, werden erwartet?

2021-07-06 19:25 UTC, Allaman commented on README-de.md
> +* Wie viele Ersuchen erwarten wir pro Sekunde?
Wie viele Anfragen ...

2021-07-06 19:25 UTC, Allaman commented on README-de.md
> +* Was ist die erwartete Lese-zu-Schreib-Verhältnis?
Was ist das erwartete Lese/Schreib-Verhältnis

2021-07-06 19:25 UTC, Allaman commented on README-de.md
> +### Schritt 2: Schafft ein höher Entwurf
Entwerfe ein Grobdesign

2021-07-06 19:25 UTC, Allaman commented on README-de.md
> +Umreiße ein höher Entwurf mit alle wichtige Komponenten.
.. einen groben Entwurf mit ...

2021-07-06 19:25 UTC, Allaman commented on README-de.md
> +* Gründen deine Ideen
Begründe deine Ideen

2021-07-06 19:25 UTC, Allaman commented on README-de.md
> +### Schritt 3: Entwurft wichtige Komponenten
Entwerfe Kernkomponenten

2021-07-06 19:25 UTC, Allaman commented on README-de.md
> +Einzutaucht in den Einzelheiten für jedes wichtiges Komponent.  Zum Beispiel, wenn du musst [design a url shortening service](solutions/system_design/pastebin/README.md), diskutiert:
Gehe für jede Kernkomponente ins Detail. Wenn du zum []() gefragt wird dann erläutere:

2021-07-06 19:25 UTC, Allaman commented on README-de.md
> +* Ein hash des volles url generieren und speichern
Generierung und Speicherung von hashes einer vollen URL

2021-07-06 19:25 UTC, Allaman commented on README-de.md
> +    * Hash collisions
Hashkollisionen

2021-07-06 19:25 UTC, Allaman commented on README-de.md
> +    * SQL or NoSQL
oder

2021-07-06 19:25 UTC, Allaman commented on README-de.md
> +    * Database schema
Datenbankschema

2021-07-06 19:25 UTC, Allaman commented on README-de.md
> +* Ein hashed url zu volles url übersetzen
Zuordnung einer hashed URL zu einer vollen URL

2021-07-06 19:25 UTC, Allaman commented on README-de.md
> +    * Database lookup
Datenbankabfragen

2021-07-06 19:25 UTC, Allaman commented on README-de.md
> +### Schritt 4: Skaliert den Entwurf
Skaliere ...

2021-07-06 19:25 UTC, Allaman commented on README-de.md
> +Identifiziert und addressiert Engpassen, angesichts der Grenzen.  Zum Beispiel, brauchst du die folgende um Probleme der Skalierung addressieren?
Identifiziere und adressiere Engpässe angesichts der Einschränkungen. Brauchst du zum Beispiel die folgenden Komponenten um ein Problem der Skalierbarkeit zu adressieren?

2021-07-06 19:25 UTC, Allaman commented on README-de.md
> +Diskutiert potentielle Lösungen und Abtauschen.  Alles ist ein Abtausch.  Addressiert Engpassen mit [principles of scalable system design](#index-of-system-design-topics).
Diskutiere potentielle Lösungen und trade-offs. Alles ist ein trade-off. Adressiere Engpässe mit ...

Anmerkung: Trade-off  ist extrem schwer ins Deutsch zu übersetzen :(

2021-07-06 19:25 UTC, Allaman commented on README-de.md
> +### Back-of-the-envelope calculations
Überschlagsrechnung

2021-07-06 19:25 UTC, Allaman commented on README-de.md
> +Du wirst vielleicht einige Schätzungen von Hand vorzunehmen gebeten.  Hinweist zu [Appendix](#appendix) um die folgende Ressourcen zu sehen:
Du wirst vielleicht einige Schätzungen aus dem Kopf vornehmen müssen. Schaue dir das []() für folgende Quellen an:

2021-07-06 19:25 UTC, Allaman commented on README-de.md
> +Schau die folgende Links um eine bessere Idee was erwarten zu haben:
Schaue dir die folgenden Links an um eine bessere Idee von dem was dich erwartet zu bekommen:

2021-07-19 02:25 UTC, JacobK233811 commented on README-de.md
> +Diskutiert potentielle Lösungen und Abtauschen.  Alles ist ein Abtausch.  Addressiert Engpassen mit [principles of scalable system design](#index-of-system-design-topics).
Alles gut. Ich werde es nur "trade-off" schreiben wie du empfehlst.

2021-07-19 02:30 UTC, merged